# - MENÚES
def principal():
    print("------------------------------------------")
    print(" - SELECCIONE UNA OPCIÓN - ")
    print("------------------------------------------")
    print("")
    print("[1] - Lista y modificación de jugadores")
    print("")
    print("[2] - Alta de jugadores")
    print("")
    print("[3] - Baja de jugadores")
    print("")
    print("[4] - Ordenar por goles")
    print("")
    print("[5] - Ordenar por partidos jugados")
    print("")
    print("[0] - Salir")
    print("")
    print("------------------------------------------")
    
def modify():
    print("")
    print("-------------------------------")
    print("")
    print(" - SELECCIONE UNA OPCIÓN - ")
    print("")
    print("[1] - Modificar")
    print("")
    print("[2] - Salir")
    print("")
    print("-------------------------------")
    
def sub_modify(registro):
    print("---------------------------------------")
    print(" - NOMBRE   : ", registro.nombre)
    print("")
    print(" - APELLIDO : ", registro.apellido)
    print("")
    print(" - GOLES    : ", registro.goles)
    print("")
    print(" - PARTIDOS : ", registro.partidos)
    print("")
    print(" - EDAD     : ", registro.edad)
    print("")
    print("----------------------------------------")
    print("     Especifique el campo a modificar   ")
    print("----------------------------------------")
    print("[1] - GOLES")
    print("[2] - PARTIDOS")
    print("[3] - EDAD")
    print("[4] - SALIR")    

def alta():
    print("")
    print("-------------------------------")
    print("")
    print(" - SELECCIONE UNA OPCIÓN - ")
    print("")
    print("[1] - Dar de alta un jugador")
    print("")
    print("[2] - Salir")
    print("")
    print("-------------------------------")
    
def baja():
    print("")
    print("-------------------------------")
    print("")
    print(" - SELECCIONE UNA OPCIÓN - ")
    print("")
    print("[1] - Dar de baja un jugador")
    print("")
    print("[2] - Salir")
    print("")
    print("-------------------------------")